#!/usr/bin/sh

#color palette
c1="\033[1;31m"
end="\033[1;0m"

net_pkg() {
	pack="$(which {xbps-install,apk,apt,pacman,nix,dnf,rpm,dpkg,emerge} 2>/dev/null | grep -v "not found" | awk -F/ 'NR==1{print $NF}')"
	case "${pack}" in
	"xbps-install")
		total=$(xbps-query -l | wc -l)
		;;
	"apk")
		total=$(apk search | wc -l)
		;;
	"apt")
		total=$(apt list --installed 2>/dev/null | wc -l)
		;;
	"pacman")
		total=$(pacman -Q | wc -l)
		;;
	"nix")
		total=$(nix-env -qa --installed "*" | wc -l)
		;;
	"dnf")
		total=$(dnf list installed | wc -l)
		;;
	"rpm")
		total=$(rpm -qa | wc -l)
		;;
	"emerge")
		total=$(qlist -I | wc -l)
		;;
	"")
		total="Unknown"
		;;
	esac
	echo $total
}

distro(){
	. /etc/os-release && echo ${PRETTY_NAME}
}

#user,host
printf "\n\t$c1$(whoami) @ $c1$(cat /etc/hostname)$end\n";

#os,arch
printf "\tos:\t\t"; printf "$(distro) $(uname -m)\n"

#kernel
printf "\tkernel:\t\t"; uname -r

#uptime
printf "\tuptime:\t\t"; uptime -p | sed 's/up //'

#pkg_count
printf "\tpkgs:\t\t"; printf "$(net_pkg)\n"

#memory
printf "\tmem:\t\t"; free -h | awk 'FNR == 2 {print $3}'

#shell
printf "\tshell:\t\t"; basename $SHELL
printf "\n"

#exit code 69
